### PR TITLE
fix for encoding support

### PR DESCRIPTION
**Pull request by johndpope**

### CODE REVIEW

**Comment by eldarsilver** [comment]
The fix also doesn't work for me using python 3.5.2. When I try to execute:

python execute.py

the application throws the same error:

File "execute.py", line 116, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte
 What can I do to solve this problem?

Thanks!!

**Comment by ishaanpatel-r** [comment]
Actually @eldarsilver, Siraj's code doesn't have a data folder since he is out of data-space.
You have to download a script from another link and compile the dialogues in the folder with that link in order to have the enc_train, dec_train etc. modules. 

Here's the requisites to rebuild them:
mkdir tensorflow_chatbot/data
cd tensorflow_chatbot/data
Get https://people.mpi-sws.org/~cristian/data/cornell_movie_dialogs_corpus.zip, put the *.txt files in this new data/ dir.
git clone https://github.com/suriyadeepan/datasets.git
Edit datasets-master/seq2seq/cornell_movie_corpus/scripts/prepare_data.py and uncomment the last lines so prepare_seq2seq_files executes.
python datasets-master/seq2seq/cornell_movie_corpus/scripts/prepare_data.py
This makes {train,test}.{enc,dec}

These files are just lines of text. I guess matching line numbers between enc and dec are conversation pairs.

**Comment by eldarsilver** [comment]
Thanks for the answer but i already have created the data folder with the {train,test}.{enc,dec} files but when I try the run "python execute.py", I get the following error:

File "execute.py", line 116, in train
enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte

I don't know how to solve this issue using Python 3.5 and Tensorflow v0.11.0rc2

Thanks again

**Comment by mcndt** [comment]
I'm getting the same error, even with the new code. Using Python 3.5 and Tensorflow 0.12.0rc0. Running on the Ubuntu subsystem on a Windows 10 machine. Here's the log:

Mode : train

Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 309, in <module>
    train()
  File "execute.py", line 123, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/mnt/d/git-projects/tensorflow_chatbot/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/mnt/d/git-projects/tensorflow_chatbot/data_utils.py", line 112, in data_to_token_ids
    vocab, _ = initialize_vocabulary(vocabulary_path)
  File "/mnt/d/git-projects/tensorflow_chatbot/data_utils.py", line 87, in initialize_vocabulary
    rev_vocab.extend(f.readlines())
(...)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte

**Comment by Niko2756** [comment]
you have to run the script is python 2.7 that is how i got rid of it and the script ran

**Comment by anshchauhan** [comment]
Well I'm pretty frustrated with this stupid error.  Has anyone found any solution? It almost took my whole day.

  File "execute.py", line 309, in <module>
    train()
  File "execute.py", line 123, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/home/ansh/py-codebase/tensorflow_chatbot/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/home/ansh/py-codebase/tensorflow_chatbot/data_utils.py", line 112, in data_to_token_ids
    vocab, _ = initialize_vocabulary(vocabulary_path)
  File "/home/ansh/py-codebase/tensorflow_chatbot/data_utils.py", line 87, in initialize_vocabulary
    rev_vocab.extend(f.readlines())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/lib/io/file_io.py", line 131, in readlines
    s = self.readline()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/lib/io/file_io.py", line 124, in readline
    return compat.as_str_any(self._read_buf.ReadLineAsString())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte

**Comment by ishaanpatel-r** [comment]
Run it with python2.7 and not python 3.5.
Use only python execute.py and not pyhton3 execute.py

Also please go through above solutions.

**Pull request merged**
